name: CI
on: workflow_call

jobs:
  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🎨 Run prettier
        run: yarn ci:prettier

  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🧹 Run eslint
        run: yarn ci:eslint

  typescript:
    name: typescript
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🎨 Run typescript compiler (tsc)
        run: yarn ci:tsc
