name: preview
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '.github/ISSUE_TEMPLATE/*'

defaults:
  run:
    shell: bash

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml # use the callable ci job to run CI checks

  publish_expo_update:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/expo/update.yaml
        with:
          pull_request: ${{ github.event.number }}
          channel: 'pr-${{ github.event.number }}'
          message: '${{ github.event.pull_request.title }}'
          expo_token: ${{ secrets.EXPO_TOKEN }}
