name: preview
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '.github/ISSUE_TEMPLATE/*'

jobs:
  # ci:
  #   uses: ./.github/workflows/ci.yaml # use the callable ci job to run CI checks

  publish:
    # needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🚀 Publish preview
        id: eas-update
        run: |
          output=`eas update --branch=pr-${{ github.event.number }} --message '${{ github.event.pull_request.title }}' --non-interactive --json | jq -c`
          echo $output
          ios_id=`echo $output | jq '.[] | select(.platform == "ios") | .id' | tr -d '"'`
          echo $ios_id
          android_id=`echo $output | jq '.[] | select(.platform == "android") | .id' | tr -d '"'`
          echo $android_id
          echo "ios_url=exp://u.expo.dev/update/$ios_id" >> $GITHUB_OUTPUT
          echo "android_url=exp://u.expo.dev/update/$android_id" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT

      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"

      # - name: 💬 Comment preview
      #   uses: expo/expo-github-action/preview-comment@v7
      #   with:
      #     channel: pr-${{ github.event.number }}

      - name: Find existing preview comment (if any)
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.number }}
          body-includes: Preview in Expo Go

      - name: Update preview comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.number }}
          edit-mode: replace
          body: |
            ## Preview in Expo Go
            Outputs ${{ steps.eas-update.outputs }}
            The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}

            ### iOS
            ${{ steps.eas-update.outputs.ios_url }}
            <a href="${{ steps.eas-update.outputs.ios_url }}"><img src="https://api.qrserver.com/v1/create-qr-code/?size=512x512&data=${{ steps.eas-update.outputs.ios_url }}" height="512px" width="512px" /></a>

            ### Android
            ${{ steps.eas-update.outputs.android_url }}
            <a href="${{ steps.eas-update.outputs.android_url }}"><img src="https://api.qrserver.com/v1/create-qr-code/?size=512x512&data=${{ steps.eas-update.outputs.android_url }}" height="512px" width="512px" /></a>
