name: preview
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '.github/ISSUE_TEMPLATE/*'

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml # use the callable ci job to run CI checks

  publish:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🚀 Publish preview
        id: eas-update
        run: |
          output=`eas update --branch=pr-${{ github.event.number }} --message '${{ github.event.pull_request.title }}' --non-interactive --json | jq -c`
          ios_id=`echo $output | jq -r '.[] | select(.platform == "ios") | .id'`
          android_id=`echo $output | jq -r '.[] | select(.platform == "android") | .id'`
          echo "ios_id=$ios_id" >> $GITHUB_OUTPUT
          echo "android_id=$android_id" >> $GITHUB_OUTPUT
          echo "new_ios_id=$( jq --raw-output '.[] | select(.platform == "ios" ) | .id ' <<<"${output}" )" >> "${GITHUB_OUTPUT}"
          echo "new_android_id=$( jq --raw-output '.[] | select(.platform == "android" ) | .id ' <<<"${output}" )" >> "${GITHUB_OUTPUT}"

      - name: Find existing preview comment (if any)
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.number }}
          body-includes: Preview in Expo Go

      - name: Update preview comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.number }}
          edit-mode: replace
          body: |
            ## Preview in Expo Go

            - ${{ steps.eas-update.outputs.ios_id }}
            - ${{ steps.eas-update.outputs.new_ios_id }}
            - ${{ steps.eas-update.outputs.android_id }}
            - ${{ steps.eas-update.outputs.new_android_id }}

            iOS | Android
            --- | ---
            ![qrcode](https://qr.expo.dev/eas-update?updateId=${{ steps.eas-update.outputs.ios_id }}&appScheme=exp&host=u.expo.dev) | ![qrcode](https://qr.expo.dev/eas-update?updateId=${{ steps.eas-update.outputs.ios_id }}&appScheme=exp&host=u.expo.dev)
            `exp://u.expo.dev/update/${{ steps.eas-update.outputs.ios_id }})` | `exp://u.expo.dev/update/${{ steps.eas-update.outputs.android_id }})`
