name: publish-build
on:
  workflow_dispatch: {}
  push:
    branches:
      - preview
      - release

defaults:
  run:
    shell: bash

jobs:

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup build environment
        uses: ./.github/actions/setup
        with:
          install_expo: true
          expo_token: ${{ secrets.EXPO_TOKEN }}

      - name: 🚀 Build Android app
        env:
          IOS_USER_ID: ${{ secrets.IOS_USER_ID }}
          IOS_TEAM_ID: ${{ secrets.IOS_TEAM_ID }}
          IOS_APP_ID: ${{ secrets.IOS_APP_ID }}
          PROFILE: ${{ github.ref_name }}
          PLATFORM: 'ios'
        run: ./eas_build_and_submit.sh
