name: publish-update
on:
  workflow_dispatch: {}
  push:
    branches:
      - preview
      - release
      - main

defaults:
  run:
    shell: bash

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml # use the callable ci job to run CI checks

  publish-update-bundle:
    needs: [ci]
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: $ {{ secrets.SENTRY_AUTH_TOKEN }}
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: Publish EAS update
        uses: ./.github/actions/expo/update
        with:
          channel: ${{ github.ref_name }}
          message: '${{ github.sha || github.ref_name }}'
          expo_token: ${{ secrets.EXPO_TOKEN }}
          sentry_dsn: ${{ secrets.EXPO_PUBLIC_SENTRY_DSN }}
          posthog_api_key: ${{ secrets.EXPO_PUBLIC_POSTHOG_API_KEY }}
          mixpanel_token: ${{ secrets.EXPO_PUBLIC_MIXPANEL_TOKEN }}
